# a workflow that will loop over the specified playlist once every 24 hours. Results stored inside duplicates.txt

name: check for duplicates

on:
  # job runs on push event
  push:
  
  # job also runs scheduled
  schedule:
    # runs the cron job at 10:22 every day UTC Time (12:22 EET)
     - cron: '22 10 * * *'

  #N.B!! each job needs to start by checking out current repo first!!

jobs:
  run-bash-file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
        with:
          #${{ secrets.GITHUB_TOKEN }} --> GITHUB_TOKEN works only on default branch.
          #therefore I have created a secret for this repository called 'PERSONAL_TOKEN'
          # Important!! I changed to 'token' from 'personal_token' and it worked!

          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: master

      - name: install youtube-dl
        run:  pip install --upgrade youtube-dl

        # runs the bash file with a hardcoded playlist
        # username and pass set as hidden variables for this repository (YT_USERNAME and YT_PASS)
      - name: run bash-file from command line
        run: |  
        
          ./script.bash https://www.youtube.com/playlist?list=PLGC6q23peGMGHyrd3Vjpfz98S8gz6kiI_ ${{ secrets.YT_USERNAME }} ${{ secrets.YT_PASS }} cookies.txt
          
      - name: save Results
      # changing from personal credentials to GitHub credentials
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Updating duplicates.txt")
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
