# a workflow that will loop over the specified playlist
# once every 24 hours. Results to be displayed as a push 
# notification or something


name: check for duplicates

on: 
  push:
  

  #schedule:
    # runs the cron job at 00:00 every day
  #  - cron: '0 0 * * *'

  #N.B!! each job needs to start by checking out current repo first!!

jobs:
  run-bash-file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
        with:
          #${{ secrets.GITHUB_TOKEN }} --> GITHUB_TOKEN works only on default branch..
          #therefore I have created a secret for this repository called 'PERSONAL_TOKEN'
          # Important!! I changed to 'token' from 'personal_token' and it worked!

          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: master

      - name: install youtube-dl
        run:  pip install --upgrade youtube-dl

      - name: run bash-file from command line
        run: |
          ./script.bash https://www.youtube.com/playlist?list=PLHr2orNvQFeVfkULTziDUO5MhcxW4nSiR
      
      - name: save Results
      # changing from personal credentials to github credentials
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Updating duplicates.txt")
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:

          #${{ secrets.GITHUB_TOKEN }} --> GITHUB_TOKEN works only on default branch..
          #therefore I have created a secret for this repository called 'PERSONAL_TOKEN'
          # Important!! I changed to 'token' from 'personal_token' and it worked!

          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: master
